//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.21 at 05:04:36 PM AEDT 
//


package com.test.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="gcdList" type="{http://test.com/soap}gcdList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gcdList"
})
@XmlRootElement(name = "getGcdListResponse")
public class GetGcdListResponse {

    @XmlElement(required = true)
    protected GcdList gcdList;

    /**
     * Gets the value of the gcdList property.
     * 
     * @return
     *     possible object is
     *     {@link GcdList }
     *     
     */
    public GcdList getGcdList() {
        return gcdList;
    }

    /**
     * Sets the value of the gcdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GcdList }
     *     
     */
    public void setGcdList(GcdList value) {
        this.gcdList = value;
    }

}
